### PR TITLE
Run bindgen at build time.

### PR DESCRIPTION
**Pull request by emilio**
This prevents the bindings from getting outdated.

### CODE REVIEW

**Comment by jdm** [comment]
Appveyor is displeased by your offering.

**Comment by SimonSapin** [comment]
This is a significant dependency to add, even build-time only. Why is this preferable to shipping generated bindings? I expect ANGLE to be updated very infrequently.

**Comment by emilio** [comment]
The idea was to be able to poke at structs / classes directly independently of the architecture. In particular, @gootorov was looking into poking at a uniform's type.

It's probably not a big deal, and we can add maybe just more FFI for it... I don't care that much TBH.

@jrmuizel thanks, look like MSVC errored at auto return type deduction.

**Comment by SimonSapin** [comment]
So, I just tried it and the compilation time for bindgen is not as bad as I remember from the time it used syntex. That only leaves the new requirement of having a recent enough version of libclang installed, though I don’t know how much of a problem that is in practice. I think that Servo and Wrench would be affected, they’re the two users of this crate and as far as I can tell neither of them build-depends on bindgen so far.

Would this code relying on a uniform’s type be new functionality that lives in this crate? Where is it to be used?

**Comment by emilio** [comment]
> Personally, I'd prefer to not pay the build time cost and the libclang requirement for something that we can reasonably run only when the ANGLE code is updated.

Well, sure. The issue is that if there are types which have different layout depending on the architecture, then we'll mess up. But I guess we can audit the generated bindings manually for now.

**Comment by sagudev** [comment]
Done in #65

**Pull request closed without merging**
