### PR TITLE
Fix a few FFI constants

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by jdm** [comment]
o.O
@bors-servo r+

**Comment by SimonSapin** [comment]
Is this the result of re-running bindgen in `generate_bindings.sh`?

**Comment by nox** [comment]
No, I kinda forgot this existed.

**Comment by SimonSapin** [comment]
Manually modifying generated files isn’t good, this fix will likely get lost next time someone needs to run the script again to update bindings for some other reason.

**Comment by nox** [comment]
@SimonSapin With the latest bindgen release, the bindings are mostly the same if you regenerate them.

```diff
--- i/src/shaders/bindings.rs
+++ w/src/shaders/bindings.rs
@@ -1,19 +1,20 @@
 /* automatically generated by rust-bindgen */

-pub type __uint64_t = ::std::os::raw::c_ulong;
-pub type khronos_uint64_t = u64;
+pub const SHRT_MAX: u32 = 32767;
+pub const SHRT_MIN: i32 = -32768;
+pub type std_array___self = u8;
 pub type std_array_value_type = u8;
-pub type std_array_pointer = u8;
-pub type std_array_const_pointer = u8;
 pub type std_array_reference = u8;
 pub type std_array_const_reference = u8;
 pub type std_array_iterator = u8;
 pub type std_array_const_iterator = u8;
+pub type std_array_pointer = u8;
+pub type std_array_const_pointer = u8;
 pub type std_array_[m
 pub type std_array_difference_type = u64;
 pub type std_array_reverse_iterator = u8;
 pub type std_array_const_reverse_iterator = u8;
-pub type std_array__AT_Type = u8;
+pub type khronos_uint64_t = u64;
 pub type ShCompileOptions = u64;
 #[repr(u32)]
 #[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
```

**Comment by SimonSapin** [comment]
Meaning that new bindgen also makes the same changes you made in this PR? (Replacing the `static mut` with a `const`, and giving those zero-valued `const`s the proper value.) If so good, my concern is resolved.

**Comment by nox** [comment]
Yep!

**Pull request merged**
